INSERT INTO `pais` (Nombre, Descripcion) VALUES 
	('Venezuela', 'LatinoAmerica'), 
	('Argentina', 'LatinoAmerica'), 
	('Estados Unidos', 'NorteAmerica'), 
	('Mexico', 'Latinoamerica'), 
	('Canada', 'NorteAmerica'), 
	('España', 'Europa'), 
	('Portugal', 'Europa'), 
	('Japon', 'Asia'), 
	('Colombia', 'LatinoAmerica'), 
	('Italia', 'Europa');
INSERT INTO ciudad (Nombre, Descripcion, Id_Pais) VALUES
	('Caracas', 'Capital', 1),
    ('Valencia', '', 1),
    ('Barquisimeto', '', 1),
    ('Buenos Aires', 'Capital', 2),
    ('Cordoba', '', 2),
    ('Rosario', '', 2),
    ('New York', '', 3),
    ('Chicago', '', 3),
    ('Miami', '', 3),
    ('Ciudad de Mexico', 'Capital', 4),
    ('Monterrey', '', 4),
    ('Guadalajara', '', 4),
    ('Toronto', '', 5),
    ('Montreal', '', 5),
    ('Vancouver', '', 5),
    ('Madrid', 'Capital', 6),
    ('Sevilla', '', 6),
    ('Barcelona', '', 6),
    ('Lisboa', 'Capital', 7),
    ('Oporto', '', 7),
    ('Madeira', '', 7),
    ('Tokio', 'Capital', 8),
    ('Kioto', '', 8),
    ('Osaka', '', 8),
    ('Bogota', 'Capital', 9),
    ('Medellin', '', 9),
    ('Cali', '', 9),
    ('Roma', 'Capital', 10),
    ('Florencia', '', 10),
    ('Venecia', '', 10);